global:
  smtp_from: 'alertmanager@yourdomain.com'
  smtp_smarthost: 'smtp.gmail.com:587'
  # smtp_auth_username: 'tesla.upload.manager@gmail.com'
  # smtp_auth_password: 'wlkh cxlm jrsj eiel' 
  smtp_auth_username: '{{ .Env.SMTP_AUTH_USERNAME }}' 
  smtp_auth_password: '{{ .Env.SMTP_AUTH_PASSWORD }}'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'default-email'
  routes:
  - match:
      severity: critical
    receiver: 'critical-email'
    continue: false

receivers:
- name: 'default-email'
  email_configs:
  - to: 'soheil.dalirii@gmail.com'
    send_resolved: true
    headers:
      subject: '[Alert] {{ .GroupLabels.alertname }} - {{ .GroupLabels.severity }}'

- name: 'critical-email'
  email_configs:
  - to: 'soheil.dalirii@gmail.com'
    send_resolved: true
    headers:
      subject: '[CRITICAL] {{ .GroupLabels.alertname }} - Immediate Action Required!'

inhibit_rules:
- source_match:
    alertname: 'InstanceDown'
    severity: 'critical'
  target_match:
    alertname: 'HighCPUUsage'
    severity: 'warning'
  equal: ['instance']